version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: joel
      POSTGRES_PASSWORD: 123123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app:/app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DEBUG=1
    depends_on:
      - db
volumes:
  db-data: